"""
语言字典
"""
LANG_DICTS = {
    'English': {
        'main_1': 'Ready',
        'main_2': 'Save to:',
        'main_3': 'Setup',
        'main_4': 'Add',
        'main_5': 'Use torrent name as folder name',
        'ui.action_setting_1': 'Program Settings',
        'label_status_error': 'Error occurred',
        'ui.dialog_settings_main_1': 'Settings',
        'ui.dialog_settings_main_2': 'Select Language:',
        'ui.dialog_settings_main_3': 'uTorrent Path:',
        'ui.dialog_settings_main_4': 'Download Path:',
        'ui.dialog_settings_main_5': 'Torrents Path:',
        'ui.dialog_settings_main_6': 'Main Settings',
        'ui.dialog_settings_main_7': 'Need Help?',
        'ui.dialog_settings_main_11': 'Confirm',
        'ui.dialog_settings_main_12': 'Cancel',
        'ui.dialog_settings_main_13': 'Config Saved!',
        'ui.action_add_1': 'Adding torrents...',
        'ui.action_add_2': 'Nothing added',
        'ui.action_add_3': 'torrents added',
        'ui.action_add_4': 'Searching torrents...',
    },
    '简体中文': {
        'main_1': '准备就绪',
        'main_2': '保存目录：',
        'main_3': '设置',
        'main_4': '添加',
        'main_5': '使用种子文件名作为文件夹名称',
        'ui.action_setting_1': '程序设置',
        'label_status_error': '发生错误！',
        'ui.dialog_settings_main_1': '设置页面',
        'ui.dialog_settings_main_2': '选择语言：',
        'ui.dialog_settings_main_3': 'uTorrent 路径：',
        'ui.dialog_settings_main_4': '下载根目录：',
        'ui.dialog_settings_main_5': '种子文件目录：',
        'ui.dialog_settings_main_6': '主设置',
        'ui.dialog_settings_main_7': '获取帮助',
        'ui.dialog_settings_main_11': '确认',
        'ui.dialog_settings_main_12': '取消',
        'ui.dialog_settings_main_13': '配置保存成功',
        'ui.action_add_1': '正在添加种子...',
        'ui.action_add_2': '没有添加任何种子',
        'ui.action_add_3': '个种子已添加',
        'ui.action_add_4': '搜索种子...',
    },
}
